# Generated by Django 6.0.5 on 2026-05-31 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=255)),
                ('quota_mb', models.PositiveIntegerField(default=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain')),
            ],
            options={
                'ordering': ['domain__name', 'local_part'],
                'unique_together': {('domain', 'local_part')},
            },
        ),
    ]
